const states=["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara","Federal Capital Territory"];
const cats=["Electrical","Plumbing","AC & Cooling","Generator","Phone & Electronics","Mechanic","Car Services","Cleaning","Painting","Carpentry","Appliance Repair","Construction","Technology","Moving & Delivery","Beauty & Personal"];
const providers=[
 {name:"Ade Electrical Services",cat:"Electrical",state:"Lagos",area:"Ikeja",rating:4.9,jobs:128,verified:true,price:"From ₦15,000"},
 {name:"PrimeFix Plumbing",cat:"Plumbing",state:"Lagos",area:"Lekki",rating:4.8,jobs:96,verified:true,price:"From ₦12,000"},
 {name:"CoolTech Services",cat:"AC & Cooling",state:"Federal Capital Territory",area:"Wuse",rating:4.7,jobs:74,verified:true,price:"From ₦18,000"}
];
let state={page:"home",service:"",location:"",request:null,quote:null};
const A=document.querySelector("#app");
const options=(a,selected="")=>a.map(x=>`<option ${x===selected?"selected":""}>${x}</option>`).join("");
function nav(){return `<nav class="nav"><div class="brand">NaijaHelp</div><div class="navlinks"><button onclick="go('home')">Home</button><button onclick="go('requests')">Requests</button><button onclick="go('messages')">Messages</button><button onclick="go('provider')">Provider</button></div></nav>`}
function layout(body){A.innerHTML=nav()+`<main class="wrap">${body}</main>`}
function go(p){state.page=p;render()}
function render(){
 if(state.page==="home") home();
 if(state.page==="search") search();
 if(state.page==="request") request();
 if(state.page==="quotes") quotes();
 if(state.page==="booking") booking();
 if(state.page==="requests") requests();
 if(state.page==="messages") messages();
 if(state.page==="provider") provider();
}
function home(){layout(`<section class="hero"><span class="badge">🇳🇬 NIGERIA-WIDE MARKETPLACE</span><h1>Find trusted help near you.</h1><p>Search local professionals, send a request and compare quotes.</p></section><div class="card"><h2>What do you need?</h2><div class="row"><label><span class="label">Service</span><select id="svc">${options(cats)}</select></label><label><span class="label">State</span><select id="st">${options(states)}</select></label></div><label><span class="label">City / Area</span><input class="input" id="area" placeholder="e.g. Ikeja, Wuse, GRA"></label><br><button class="btn primary" onclick="find()">Find Help</button></div><div class="grid">${cats.slice(0,6).map((c,i)=>`<div class="card"><b>${["⚡","🔧","❄️","⚙️","📱","🚗"][i]} ${c}</b><p class="muted small">Find providers and request this service.</p><button class="btn gold" onclick="quick('${c}')">Explore</button></div>`).join("")}</div>`)}
function find(){state.service=document.querySelector("#svc").value;state.location=document.querySelector("#area").value;go("search")}
function quick(c){state.service=c;go("search")}
function search(){let list=providers.filter(p=>!state.service||p.cat===state.service);layout(`<div class="tabs"><button class="on">Providers</button><button>Requests</button></div><h1>${state.service||"Service providers"}</h1><p class="muted">${state.location||"Nigeria-wide"} · Matching providers</p><div>${list.length?list.map(p=>`<div class="card provider"><div><h3>${p.name} ${p.verified?'<span class="badge">✓ Verified</span>':""}</h3><div class="stars">★★★★★ <b>${p.rating}</b> · ${p.jobs} jobs</div><p class="muted">${p.cat} · ${p.area}, ${p.state}</p></div><div><div class="price">${p.price}</div><button class="btn primary" onclick="makeRequest('${p.name}')">Request Service</button></div></div>`).join(""):`<div class="card empty">No matching providers yet. You can still create a request and let matching providers respond.<br><br><button class="btn primary" onclick="go('request')">Create Request</button></div>`}</div>`)}
function makeRequest(provider){state.request={provider,service:state.service||"General service",location:state.location};go("request")}
function request(){layout(`<h1>Request a service</h1><p class="muted">Describe the job so providers can understand what you need.</p><div class="card"><label><span class="label">Service</span><select id="rsvc">${options(cats,state.service)}</select></label><label><span class="label">State</span><select id="rst">${options(states)}</select></label><label><span class="label">City / Area</span><input class="input" id="rarea" value="${state.location||""}" placeholder="Area"></label><label><span class="label">Describe the job</span><textarea id="desc" rows="5" placeholder="What needs to be done?"></textarea></label><div class="row"><label><span class="label">Preferred date</span><input class="input" type="date" id="date"></label><label><span class="label">Budget (optional)</span><input class="input" id="budget" placeholder="e.g. ₦20,000"></label></div><br><button class="btn primary" onclick="submitRequest()">Submit Request</button></div>`)}
function submitRequest(){state.service=document.querySelector("#rsvc").value;state.location=document.querySelector("#rarea").value;state.request={service:state.service,location:state.location,status:"REQUESTED",id:"NH-"+Math.floor(100000+Math.random()*900000)};go("quotes")}
function quotes(){layout(`<h1>Request ${state.request?.id||"NH-000000"}</h1><p class="muted">Status: REQUESTED · ${state.request?.service||""} · ${state.request?.location||"Nigeria"}</p><div class="card"><h2>Provider quotes</h2><div class="card"><h3>Ade Electrical Services <span class="badge">✓ Verified</span></h3><p class="muted">Proposed work · 2 hours · Available tomorrow</p><div class="price">₦25,000</div><button class="btn primary" onclick="acceptQuote()">Accept Quote</button> <button class="btn gold">Ask Question</button></div></div>`)}
function acceptQuote(){state.quote={provider:"Ade Electrical Services",amount:"₦25,000",status:"BOOKED"};go("booking")}
function booking(){layout(`<h1>Job booking</h1><div class="card"><span class="badge">BOOKED</span><h2>${state.quote.provider}</h2><p>Agreed price: <b>${state.quote.amount}</b></p><p class="muted">Your job is now scheduled. Keep communication inside NaijaHelp.</p><div class="status"><span class="active">Requested</span><span class="active">Quoted</span><span class="active">Booked</span><span>On the Way</span><span>In Progress</span><span>Completed</span><span>Reviewed</span></div><button class="btn primary" onclick="go('messages')">Message Provider</button></div>`)}
function requests(){layout(`<h1>My Requests</h1><div class="card"><b>${state.request?.id||"No requests yet"}</b><p class="muted">${state.request?.service||"Create a request to start."}</p>${state.request?`<span class="badge">${state.quote?"BOOKED":"REQUESTED"}</span>`:""} </div>`)}
function messages(){layout(`<h1>Messages</h1><div class="card"><h3>${state.quote?.provider||"NaijaHelp conversation"}</h3><p class="muted">Job-linked conversation. Provider and customer messages will appear here.</p><div class="card">Hello! Thanks for choosing NaijaHelp.</div><input class="input" placeholder="Type a message..."></div>`)}
function provider(){layout(`<section class="hero"><span class="badge">PROVIDER</span><h1>Grow your local service business.</h1><p>Set your service areas, receive matching requests, send quotes and build your reputation.</p><button class="btn gold" onclick="alert('Provider onboarding module next.')">Start Provider Onboarding</button></section><div class="grid"><div class="card"><h3>New opportunities</h3><div class="price">12</div></div><div class="card"><h3>Pending quotes</h3><div class="price">4</div></div><div class="card"><h3>Upcoming jobs</h3><div class="price">3</div></div></div>`)}
render();