import express, { Request, Response, NextFunction } from "express";
import cors from "cors";
import helmet from "helmet";
import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import crypto from "crypto";
import path from "path";
import { createServer } from "http";
import { Server } from "socket.io";
import { PrismaClient, UserRole, UserStatus, RequestStatus, QuoteStatus, BookingStatus, PaymentStatus, NotificationType, ReportStatus, ReportTargetType, VerificationStatus, VerificationDocumentType } from "@prisma/client";
import { z } from "zod";

dotenv.config();
const prisma = new PrismaClient();
const app = express();
app.disable("x-powered-by");
if (process.env.TRUST_PROXY === "true") app.set("trust proxy", 1);
const httpServer = createServer(app);
const allowedOrigins = (process.env.CORS_ORIGINS || "http://localhost:5500,http://localhost:3000").split(",").map(x=>x.trim()).filter(Boolean);
const io = new Server(httpServer, { cors:{origin:allowedOrigins, credentials:true} });
const PORT = Number(process.env.PORT || 4000);
const JWT_SECRET = process.env.JWT_SECRET || "dev-only-secret-change-me";
const isProduction = process.env.NODE_ENV === "production";
if (isProduction && JWT_SECRET === "dev-only-secret-change-me") throw new Error("JWT_SECRET must be set in production");

app.use(helmet());
app.use(cors({origin:(origin,cb)=>!origin || allowedOrigins.includes(origin)?cb(null,true):cb(new Error("Origin not allowed")),credentials:true}));
app.use((req:any,res,next)=>{ const id=req.headers["x-request-id"] || crypto.randomUUID(); req.requestId=String(id); res.setHeader("X-Request-Id",String(id)); next(); });
app.use(express.json({limit:"1mb", verify:(req:any,_res,buf)=>{req.rawBody=Buffer.from(buf);}}));

const buckets = new Map<string,{count:number,reset:number}>();
function rateLimit(limit:number, windowMs:number){ return (req:any,res:any,next:any)=>{ const key=`${req.ip}:${req.path}`; const now=Date.now(); const b=buckets.get(key); if(!b || now>b.reset){ buckets.set(key,{count:1,reset:now+windowMs}); return next(); } if(b.count>=limit) return res.status(429).json({error:"Too many requests. Try again shortly."}); b.count++; next(); }; }
const publicLimit=rateLimit(120,60_000); const authLimit=rateLimit(20,60_000); const messageLimit=rateLimit(30,60_000);

function signToken(user:any){ return jwt.sign({id:user.id,role:user.role},JWT_SECRET,{expiresIn:"7d"}); }
function auth(req:any,res:any,next:any){ const raw=req.headers.authorization?.replace("Bearer ",""); if(!raw)return res.status(401).json({error:"Authentication required"}); try{req.user=jwt.verify(raw,JWT_SECRET); next();}catch{return res.status(401).json({error:"Invalid token"});} }
function requireRole(...roles:UserRole[]){ return (req:any,res:any,next:any)=>roles.includes(req.user?.role)?next():res.status(403).json({error:"Insufficient permissions"}); }
function cleanError(err:any):{status:number,error:string,details?:any}{ if(err instanceof z.ZodError)return {status:400,error:"Invalid input",details:err.flatten()}; if(err?.code==="P2002")return {status:409,error:"A record with this value already exists"}; console.error(err); return {status:500,error:"Internal server error"}; }
async function notify(userId:string,type:NotificationType,title:string,body:string){ const n=await prisma.notification.create({data:{userId,type,title,body}}); io.to(`user:${userId}`).emit("notification",n); return n; }
async function audit(adminId:string,action:string,targetType:string,targetId:string,metadata?:any){ await prisma.adminAuditLog.create({data:{adminId,action,targetType,targetId,metadata}}); }

app.get("/health",(_,res)=>res.json({ok:true,service:"naijahelp-api",version:"1.4.0-staging",environment:process.env.NODE_ENV||"development"}));
app.get("/ready",async(_,res)=>{ try { await prisma.$queryRaw`SELECT 1`; res.json({ok:true,database:"up"}); } catch { res.status(503).json({ok:false,database:"down"}); } });

app.post("/api/auth/register",authLimit,async(req,res)=>{try{const body=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(8),role:z.enum(["CUSTOMER","PROVIDER"]).default("CUSTOMER"),fullName:z.string().trim().min(2).optional(),businessName:z.string().trim().min(2).optional(),phone:z.string().trim().min(7).max(20).optional()}).parse(req.body); const exists=await prisma.user.findFirst({where:{OR:[{email:body.email},...(body.phone?[{phone:body.phone}]:[])]}}); if(exists)return res.status(409).json({error:"Email or phone already registered"}); const passwordHash=await bcrypt.hash(body.password,12); const user=await prisma.user.create({data:{email:body.email,phone:body.phone,passwordHash,role:body.role,customer:body.role==="CUSTOMER"?{create:{fullName:body.fullName||"Customer"}}:undefined,provider:body.role==="PROVIDER"?{create:{businessName:body.businessName||"Provider"}}:undefined}}); res.status(201).json({token:signToken(user),user:{id:user.id,email:user.email,role:user.role}});}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error,details:x.details});}});

app.post("/api/auth/login",authLimit,async(req,res)=>{try{const body=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string()}).parse(req.body); const user=await prisma.user.findUnique({where:{email:body.email}}); if(!user || !(await bcrypt.compare(body.password,user.passwordHash)))return res.status(401).json({error:"Invalid credentials"}); if(user.status!==UserStatus.ACTIVE)return res.status(403).json({error:`Account is ${user.status.toLowerCase()}`}); await notify(user.id,NotificationType.SECURITY,"New login","Your NaijaHelp account was signed in."); res.json({token:signToken(user),user:{id:user.id,email:user.email,role:user.role}});}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error});}});

app.get("/api/locations/states",publicLimit,async(_,res)=>res.json(await prisma.state.findMany({orderBy:{name:"asc"}})));
app.get("/api/locations/states/:id/lgas",publicLimit,async(req,res)=>res.json(await prisma.lGA.findMany({where:{stateId:req.params.id},orderBy:{name:"asc"}})));
app.get("/api/locations/lgas/:id/areas",publicLimit,async(req,res)=>res.json(await prisma.area.findMany({where:{lgaId:req.params.id},orderBy:{name:"asc"}})));
app.get("/api/categories",publicLimit,async(_,res)=>res.json(await prisma.category.findMany({include:{services:true},orderBy:{name:"asc"}})));

app.get("/api/providers",publicLimit,async(req,res)=>{const serviceId=typeof req.query.serviceId==="string"?req.query.serviceId:undefined; const stateId=typeof req.query.stateId==="string"?req.query.stateId:undefined; const lgaId=typeof req.query.lgaId==="string"?req.query.lgaId:undefined; const areaId=typeof req.query.areaId==="string"?req.query.areaId:undefined; const providers=await prisma.providerProfile.findMany({where:{verificationStatus:VerificationStatus.VERIFIED,user:{status:UserStatus.ACTIVE},...(serviceId?{services:{some:{serviceId}}}:{}),...(stateId?{serviceAreas:{some:{stateId}}}:{}),...(lgaId?{serviceAreas:{some:{lgaId}}}:{}),...(areaId?{serviceAreas:{some:{areaId}}}:{})},include:{services:{include:{service:true}},serviceAreas:true},orderBy:{rating:"desc"},take:50});res.json(providers);});

app.post("/api/requests",auth,requireRole(UserRole.CUSTOMER),async(req:any,res)=>{try{const body=z.object({serviceId:z.string(),stateId:z.string().optional(),lgaId:z.string().optional(),areaId:z.string().optional(),title:z.string().trim().min(3).max(120),description:z.string().trim().min(5).max(5000),budgetMin:z.number().int().nonnegative().optional(),budgetMax:z.number().int().nonnegative().optional()}).parse(req.body); if(body.budgetMin!==undefined&&body.budgetMax!==undefined&&body.budgetMin>body.budgetMax)return res.status(400).json({error:"Minimum budget cannot exceed maximum budget"}); const request=await prisma.serviceRequest.create({data:{...body,customerId:req.user.id,status:RequestStatus.OPEN}}); res.status(201).json(request);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error,details:x.details});}});

app.get("/api/requests",auth,async(req:any,res)=>{const where:any=req.user.role===UserRole.CUSTOMER?{customerId:req.user.id}:{quotes:{some:{provider:{userId:req.user.id}}}}; res.json(await prisma.serviceRequest.findMany({where,include:{service:true,quotes:{include:{provider:true}},booking:{include:{payment:true}}},orderBy:{createdAt:"desc"},take:100}));});

app.post("/api/requests/:id/quotes",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{try{const provider=await prisma.providerProfile.findUnique({where:{userId:req.user.id},include:{services:true,serviceAreas:true}}); if(!provider)return res.status(404).json({error:"Provider profile not found"}); if(provider.verificationStatus!==VerificationStatus.VERIFIED)return res.status(403).json({error:"Provider verification is required before quoting"}); const request=await prisma.serviceRequest.findUnique({where:{id:req.params.id}}); if(!request || ![RequestStatus.OPEN,RequestStatus.QUOTED].includes(request.status))return res.status(404).json({error:"Request is not available for quoting"}); if(!provider.services.some(x=>x.serviceId===request.serviceId))return res.status(403).json({error:"Provider is not registered for this service"}); const covered=provider.serviceAreas.some(a=>a.areaId===request.areaId || a.lgaId===request.lgaId || a.stateId===request.stateId); if(!covered)return res.status(403).json({error:"Provider does not cover this request location"}); const body=z.object({amount:z.number().int().positive(),note:z.string().max(2000).optional()}).parse(req.body); const quote=await prisma.quote.create({data:{requestId:req.params.id,providerId:provider.id,...body}}); await prisma.serviceRequest.update({where:{id:req.params.id},data:{status:RequestStatus.QUOTED}}); await notify(request.customerId,NotificationType.QUOTE_RECEIVED,"New quote received",`A provider submitted a ₦${body.amount.toLocaleString()} quote for your request.`); res.status(201).json(quote);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error,details:x.details});}});

app.post("/api/quotes/:id/accept",auth,requireRole(UserRole.CUSTOMER),async(req:any,res)=>{try{const quote=await prisma.quote.findUnique({where:{id:req.params.id},include:{request:true}}); if(!quote || quote.request.customerId!==req.user.id)return res.status(404).json({error:"Quote not found"}); if(quote.status!==QuoteStatus.PENDING)return res.status(400).json({error:"Quote is no longer available"}); const result=await prisma.$transaction(async tx=>{await tx.quote.updateMany({where:{requestId:quote.requestId,status:QuoteStatus.PENDING},data:{status:QuoteStatus.DECLINED}}); const accepted=await tx.quote.update({where:{id:quote.id},data:{status:QuoteStatus.ACCEPTED}}); const booking=await tx.booking.create({data:{requestId:quote.requestId,providerId:quote.providerId,agreedAmount:quote.amount}}); await tx.serviceRequest.update({where:{id:quote.requestId},data:{status:RequestStatus.BOOKED}}); return {accepted,booking};}); const provider=await prisma.providerProfile.findUnique({where:{id:quote.providerId}}); if(provider)await notify(provider.userId,NotificationType.QUOTE_ACCEPTED,"Quote accepted","Your quote was accepted. Check the booking details."); res.json(result);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error});}});

async function canAccessRequest(user:any,requestId:string){const r=await prisma.serviceRequest.findUnique({where:{id:requestId},include:{booking:{include:{provider:{include:{user:true}}}},quotes:{include:{provider:{include:{user:true}}}}}}); if(!r)return null; if(user.role===UserRole.ADMIN)return r; if(user.role===UserRole.CUSTOMER&&r.customerId===user.id)return r; if(user.role===UserRole.PROVIDER&&r.quotes.some(q=>q.provider.userId===user.id))return r; if(user.role===UserRole.PROVIDER&&r.booking?.provider.userId===user.id)return r; return null; }

app.get("/api/requests/:id/messages",auth,async(req:any,res)=>{const r=await canAccessRequest(req.user,req.params.id); if(!r)return res.status(404).json({error:"Request not found"}); res.json(await prisma.message.findMany({where:{requestId:req.params.id},include:{sender:{select:{id:true,email:true,role:true}}},orderBy:{createdAt:"asc"},take:500}));});
app.post("/api/requests/:id/messages",auth,messageLimit,async(req:any,res)=>{const r=await canAccessRequest(req.user,req.params.id); if(!r)return res.status(404).json({error:"Request not found"}); try{const body=z.object({body:z.string().trim().min(1).max(5000)}).parse(req.body); const message=await prisma.message.create({data:{requestId:req.params.id,senderId:req.user.id,body:body.body},include:{sender:{select:{id:true,email:true,role:true}}}}); io.to(`request:${req.params.id}`).emit("message",message); const recipientIds=new Set<string>(); if(r.customerId!==req.user.id)recipientIds.add(r.customerId); for(const q of r.quotes)if(q.provider.userId!==req.user.id)recipientIds.add(q.provider.userId); if(r.booking?.provider.userId!==req.user.id)recipientIds.add(r.booking?.provider.userId||""); for(const id of recipientIds)if(id)await notify(id,NotificationType.MESSAGE,"New message","You have a new NaijaHelp message."); res.status(201).json(message);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error});}});

app.post("/api/bookings/:id/status",auth,async(req:any,res)=>{try{const body=z.object({status:z.enum(["CONFIRMED","IN_PROGRESS","COMPLETED","CANCELLED"])}).parse(req.body); const booking=await prisma.booking.findUnique({where:{id:req.params.id},include:{provider:{include:{user:true}},request:true}}); if(!booking)return res.status(404).json({error:"Booking not found"}); const isCustomer=booking.request.customerId===req.user.id; const isProvider=booking.provider.userId===req.user.id; const isAdmin=req.user.role===UserRole.ADMIN; if(!isCustomer&&!isProvider&&!isAdmin)return res.status(403).json({error:"Not authorized"}); const current=booking.status; const allowed=isAdmin || (isProvider && ((current===BookingStatus.CONFIRMED && [BookingStatus.IN_PROGRESS,BookingStatus.CANCELLED].includes(body.status as BookingStatus)) || (current===BookingStatus.IN_PROGRESS && body.status===BookingStatus.COMPLETED))) || (isCustomer && current===BookingStatus.CONFIRMED && body.status===BookingStatus.CANCELLED); if(!allowed)return res.status(409).json({error:"Invalid booking status transition"}); const updated=await prisma.booking.update({where:{id:booking.id},data:{status:body.status as BookingStatus}}); const map:any={CONFIRMED:RequestStatus.BOOKED,IN_PROGRESS:RequestStatus.IN_PROGRESS,COMPLETED:RequestStatus.COMPLETED,CANCELLED:RequestStatus.CANCELLED}; await prisma.serviceRequest.update({where:{id:booking.requestId},data:{status:map[body.status]}}); const customerId=booking.request.customerId; await notify(isCustomer?booking.provider.userId:customerId,body.status==="IN_PROGRESS"?NotificationType.JOB_STARTED:body.status==="COMPLETED"?NotificationType.JOB_COMPLETED:NotificationType.BOOKING_UPDATE,"Booking updated",`Booking status is now ${body.status.replace("_"," ").toLowerCase()}.`); res.json(updated);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error});}});

app.get("/api/provider/me",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>res.json(await prisma.providerProfile.findUnique({where:{userId:req.user.id},include:{services:{include:{service:true}},serviceAreas:true,documents:true}})));
app.put("/api/provider/me",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{const body=z.object({businessName:z.string().trim().min(2).max(120),bio:z.string().max(3000).optional()}).parse(req.body);res.json(await prisma.providerProfile.update({where:{userId:req.user.id},data:body}));});
app.get("/api/provider/requests",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{const p=await prisma.providerProfile.findUnique({where:{userId:req.user.id},include:{services:true,serviceAreas:true}}); if(!p)return res.status(404).json({error:"Provider profile not found"}); const serviceIds=p.services.map(x=>x.serviceId); const stateIds=p.serviceAreas.filter(x=>x.stateId).map(x=>x.stateId!); const lgaIds=p.serviceAreas.filter(x=>x.lgaId).map(x=>x.lgaId!); const areaIds=p.serviceAreas.filter(x=>x.areaId).map(x=>x.areaId!); res.json(await prisma.serviceRequest.findMany({where:{status:{in:[RequestStatus.OPEN,RequestStatus.QUOTED]},serviceId:{in:serviceIds},OR:[{areaId:{in:areaIds}},{lgaId:{in:lgaIds}},{stateId:{in:stateIds}},{stateId:null}]},include:{service:true,customer:{select:{id:true,customer:true}}},orderBy:{createdAt:"desc"},take:100}));});
app.get("/api/provider/jobs",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{const p=await prisma.providerProfile.findUnique({where:{userId:req.user.id}}); if(!p)return res.status(404).json({error:"Provider profile not found"}); res.json(await prisma.booking.findMany({where:{providerId:p.id},include:{request:{include:{service:true,customer:true}},payment:true},orderBy:{createdAt:"desc"}}));});
app.get("/api/provider/coverage",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{const p=await prisma.providerProfile.findUnique({where:{userId:req.user.id},include:{serviceAreas:true}});res.json(p?.serviceAreas||[]);});
app.put("/api/provider/coverage",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{const p=await prisma.providerProfile.findUnique({where:{userId:req.user.id}}); if(!p)return res.status(404).json({error:"Provider profile not found"}); const areas=z.array(z.object({areaType:z.enum(["STATE","LGA","AREA"]),stateId:z.string().optional(),lgaId:z.string().optional(),areaId:z.string().optional()})).max(100).parse(req.body.areas); await prisma.providerServiceArea.deleteMany({where:{providerId:p.id}}); await prisma.providerServiceArea.createMany({data:areas.map(a=>({...a,providerId:p.id}))});res.json(await prisma.providerServiceArea.findMany({where:{providerId:p.id}}));});

app.get("/api/notifications",auth,async(req:any,res)=>res.json(await prisma.notification.findMany({where:{userId:req.user.id},orderBy:{createdAt:"desc"},take:100}))); app.patch("/api/notifications/:id/read",auth,async(req:any,res)=>res.json(await prisma.notification.updateMany({where:{id:req.params.id,userId:req.user.id},data:{readAt:new Date()}})));

app.post("/api/bookings/:id/payment",auth,requireRole(UserRole.CUSTOMER),async(req:any,res)=>{const booking=await prisma.booking.findUnique({where:{id:req.params.id},include:{request:true,provider:{include:{user:true}},payment:true}}); if(!booking||booking.request.customerId!==req.user.id)return res.status(404).json({error:"Booking not found"}); if(booking.payment)return res.json(booking.payment); const payment=await prisma.payment.create({data:{bookingId:booking.id,payerId:req.user.id,payeeId:booking.provider.userId,amount:booking.agreedAmount,status:PaymentStatus.PENDING,provider:process.env.PAYSTACK_SECRET_KEY?"paystack":undefined}}); res.status(201).json({payment,checkoutRequired:true,gatewayConfigured:Boolean(process.env.PAYSTACK_SECRET_KEY)});});
app.post("/api/bookings/:id/payment/initialize",auth,requireRole(UserRole.CUSTOMER),async(req:any,res)=>{
  try{
    if(!process.env.PAYSTACK_SECRET_KEY)return res.status(503).json({error:"Payment gateway is not configured"});
    const booking=await prisma.booking.findUnique({where:{id:req.params.id},include:{request:{include:{customer:true}} ,payment:true}});
    if(!booking||booking.request.customerId!==req.user.id)return res.status(404).json({error:"Booking not found"});
    const payment=booking.payment||await prisma.payment.create({data:{bookingId:booking.id,payerId:req.user.id,payeeId:booking.provider.userId,amount:booking.agreedAmount,status:PaymentStatus.PENDING,provider:"paystack"}});
    if(payment.status===PaymentStatus.PAID)return res.json({payment,alreadyPaid:true});
    const email=booking.request.customer.email;
    const callback=process.env.PAYSTACK_CALLBACK_URL||`${process.env.PUBLIC_APP_URL||"http://localhost:4000"}/payment-callback.html`;
    const response=await fetch("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({email,amount:payment.amount*100,currency:"NGN",reference:`NH-${payment.id}-${Date.now()}`,callback_url:callback,metadata:{paymentId:payment.id,bookingId:booking.id}})});
    const data:any=await response.json();
    if(!response.ok||!data.status)throw new Error(data.message||"Paystack initialization failed");
    const updated=await prisma.payment.update({where:{id:payment.id},data:{reference:data.data.reference,status:PaymentStatus.REQUIRES_ACTION,gatewayData:data.data}});
    await prisma.paymentEvent.create({data:{paymentId:payment.id,eventType:"initialize",reference:data.data.reference,payload:data.data}});
    res.json({payment:updated,authorizationUrl:data.data.authorization_url,accessCode:data.data.access_code});
  }catch(e){const x=cleanError(e);res.status(x.status===500?502:x.status).json({error:x.status===500?"Payment gateway error":x.error});}
});

app.get("/api/bookings/:id/payment",auth,async(req:any,res)=>{const payment=await prisma.payment.findUnique({where:{bookingId:req.params.id}}); if(!payment)return res.status(404).json({error:"Payment not found"}); if(payment.payerId!==req.user.id&&payment.payeeId!==req.user.id&&req.user.role!==UserRole.ADMIN)return res.status(403).json({error:"Not authorized"}); res.json(payment);});
const paystackWebhook=async(req:any,res:any)=>{ if(!process.env.PAYSTACK_SECRET_KEY)return res.status(503).json({error:"Payment webhook is not configured"}); const sig=req.headers["x-paystack-signature"]; if(typeof sig!=="string")return res.status(401).json({error:"Missing signature"}); const raw=req.rawBody||Buffer.from(JSON.stringify(req.body)); const expected=crypto.createHmac("sha512",process.env.PAYSTACK_SECRET_KEY).update(raw).digest("hex"); const a=Buffer.from(expected), b=Buffer.from(sig); if(a.length!==b.length || !crypto.timingSafeEqual(a,b))return res.status(401).json({error:"Invalid signature"}); const reference=req.body?.data?.reference||req.body?.reference; const payment=reference?await prisma.payment.findFirst({where:{reference}}):null; if(payment){const eventType=req.body?.event||"webhook"; const existing=await prisma.paymentEvent.findFirst({where:{paymentId:payment.id,eventType,reference}}); if(!existing){const status=eventType==="charge.success"?PaymentStatus.PAID:eventType==="charge.failed"?PaymentStatus.FAILED:payment.status; await prisma.$transaction([prisma.payment.update({where:{id:payment.id},data:{status,provider:"paystack",gatewayData:req.body}}),prisma.paymentEvent.create({data:{paymentId:payment.id,eventType,reference,payload:req.body}})]);} } res.json({received:true});};
app.post("/api/payments/paystack/webhook",paystackWebhook);
app.post("/api/payments/:id/webhook",paystackWebhook);

app.post("/api/bookings/:id/reviews",auth,requireRole(UserRole.CUSTOMER),async(req:any,res)=>{try{const body=z.object({rating:z.number().int().min(1).max(5),comment:z.string().trim().max(2000).optional()}).parse(req.body); const booking=await prisma.booking.findUnique({where:{id:req.params.id}}); if(!booking||booking.status!==BookingStatus.COMPLETED)return res.status(400).json({error:"Completed booking required"}); const request=await prisma.serviceRequest.findUnique({where:{id:booking.requestId}}); if(!request||request.customerId!==req.user.id)return res.status(403).json({error:"Not authorized"}); const review=await prisma.review.create({data:{bookingId:booking.id,authorId:req.user.id,providerId:booking.providerId,...body}}); const agg=await prisma.review.aggregate({where:{providerId:booking.providerId},_avg:{rating:true},_count:{rating:true}}); await prisma.providerProfile.update({where:{id:booking.providerId},data:{rating:agg._avg.rating||0,reviewCount:agg._count.rating}}); await notify((await prisma.providerProfile.findUnique({where:{id:booking.providerId}}))!.userId,NotificationType.REVIEW_REMINDER,"New review","A customer reviewed your completed job."); res.status(201).json(review);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error});}});
app.get("/api/providers/:id/reviews",publicLimit,async(req,res)=>res.json(await prisma.review.findMany({where:{providerId:req.params.id},include:{author:{select:{id:true,customer:true}}},orderBy:{createdAt:"desc"},take:100})));

app.post("/api/reports",auth,async(req:any,res)=>{try{const body=z.object({targetType:z.enum(["USER","PROVIDER","REQUEST","BOOKING","REVIEW","MESSAGE"]),targetId:z.string(),reason:z.string().trim().min(3).max(120),details:z.string().trim().max(3000).optional()}).parse(req.body); const report=await prisma.report.create({data:{...body,reporterId:req.user.id,targetType:body.targetType as ReportTargetType}}); res.status(201).json(report);}catch(e){const x=cleanError(e);res.status(x.status).json({error:x.error});}});
app.get("/api/admin/reports",auth,requireRole(UserRole.ADMIN),async(_,res)=>res.json(await prisma.report.findMany({include:{reporter:{select:{id:true,email:true}},request:true,booking:true,review:true},orderBy:{createdAt:"desc"},take:500})));
app.patch("/api/admin/reports/:id",auth,requireRole(UserRole.ADMIN),async(req:any,res)=>{const body=z.object({status:z.enum(["OPEN","UNDER_REVIEW","RESOLVED","DISMISSED"]),adminNote:z.string().max(3000).optional()}).parse(req.body);const report=await prisma.report.update({where:{id:req.params.id},data:body as any});await audit(req.user.id,"REPORT_UPDATE","REPORT",report.id,body);res.json(report);});

app.post("/api/provider/documents",auth,requireRole(UserRole.PROVIDER),async(req:any,res)=>{const p=await prisma.providerProfile.findUnique({where:{userId:req.user.id}});if(!p)return res.status(404).json({error:"Provider profile not found"});const body=z.object({documentType:z.enum(["IDENTITY","BUSINESS_LICENSE","ADDRESS_PROOF","OTHER"]),documentUrl:z.string().url().max(2000)}).parse(req.body);const doc=await prisma.verificationDocument.create({data:{providerId:p.id,documentType:body.documentType as VerificationDocumentType,documentUrl:body.documentUrl}});res.status(201).json(doc);});
app.get("/api/admin/verification-documents",auth,requireRole(UserRole.ADMIN),async(_,res)=>res.json(await prisma.verificationDocument.findMany({include:{provider:true},orderBy:{createdAt:"desc"},take:500})));
app.patch("/api/admin/verification-documents/:id",auth,requireRole(UserRole.ADMIN),async(req:any,res)=>{const body=z.object({status:z.enum(["PENDING","VERIFIED","REJECTED"]),reviewerNote:z.string().max(2000).optional()}).parse(req.body);const doc=await prisma.verificationDocument.update({where:{id:req.params.id},data:body as any,include:{provider:true}});if(body.status!=="PENDING")await prisma.providerProfile.update({where:{id:doc.providerId},data:{verificationStatus:body.status as VerificationStatus}});await notify(doc.provider.userId,NotificationType.VERIFICATION_RESULT,"Verification update",`Your verification status is ${body.status.toLowerCase()}.`);await audit(req.user.id,"VERIFICATION_DOCUMENT_UPDATE","VERIFICATION_DOCUMENT",doc.id,body);res.json(doc);});
app.get("/api/admin/audit-logs",auth,requireRole(UserRole.ADMIN),async(req:any,res)=>res.json(await prisma.adminAuditLog.findMany({include:{admin:{select:{id:true,email:true}}},orderBy:{createdAt:"desc"},take:500})));
app.get("/api/admin/stats",auth,requireRole(UserRole.ADMIN),async(_,res)=>{const [users,providers,openRequests,completed,openReports]=await Promise.all([prisma.user.count(),prisma.providerProfile.count(),prisma.serviceRequest.count({where:{status:{in:[RequestStatus.OPEN,RequestStatus.QUOTED]}}}),prisma.booking.count({where:{status:BookingStatus.COMPLETED}}),prisma.report.count({where:{status:{in:[ReportStatus.OPEN,ReportStatus.UNDER_REVIEW]}}})]);res.json({users,providers,openRequests,completedJobs:completed,openReports});});

io.use((socket,next)=>{try{const raw=socket.handshake.auth?.token; if(!raw)return next(new Error("Authentication required")); const user:any=jwt.verify(raw,JWT_SECRET); socket.data.user=user; next();}catch{next(new Error("Invalid token"));}});
io.on("connection",socket=>{const user=socket.data.user; socket.join(`user:${user.id}`); socket.on("join_request",async(requestId:string)=>{const r=await canAccessRequest(user,requestId);if(r)socket.join(`request:${requestId}`);}); socket.on("send_message",async(payload:any)=>{const r=await canAccessRequest(user,payload?.requestId);if(!r)return; const parsed=z.object({requestId:z.string(),body:z.string().trim().min(1).max(5000)}).safeParse(payload);if(!parsed.success)return; const m=await prisma.message.create({data:{requestId:parsed.data.requestId,senderId:user.id,body:parsed.data.body},include:{sender:{select:{id:true,email:true,role:true}}}});io.to(`request:${m.requestId}`).emit("message",m);});});

const publicDir=process.env.PUBLIC_DIR||path.resolve(process.cwd(),"public");
app.use(express.static(publicDir,{index:"index.html"}));
app.get(/^(?!\/api\/|\/health|\/socket\.io).*/,(req,res,next)=>{ if(req.path.startsWith("/api/")||req.path==="/health"||req.path.startsWith("/socket.io")) return next(); res.sendFile(path.join(publicDir,"index.html"),err=>err&&next(err)); });

app.use((err: any, req: Request, res: Response, next: NextFunction) => {
httpServer.listen(PORT,()=>console.log(`NaijaHelp API v1.4.0-staging running on http://localhost:${PORT}`));
async function shutdown(signal:string){ console.log(`${signal}: shutting down`); try { await prisma.$disconnect(); } finally { httpServer.close(()=>process.exit(0)); setTimeout(()=>process.exit(1),10000).unref(); } }
process.on("SIGTERM",()=>void shutdown("SIGTERM"));
process.on("SIGINT",()=>void shutdown("SIGINT"));
